/**
 * 公開API生成スクリプト (GitHub Actions から毎時実行)
 *
 * 47都道府県庁所在地の予報を取得し、アプリと同じロジック
 * (コンセンサス予報 / 頭痛リスク / 傘予報) で計算した結果を
 * 静的JSONとして dist/api/v1/ に書き出す。GitHub Pages が
 * Access-Control-Allow-Origin: * で配信するため、誰でも
 * キー不要でブラウザから直接利用できる。
 *
 * レスポンスは全endpoint共通の envelope 形式:
 *   { success, data, error, meta }
 *
 * 実行: npm run build:api  (tsx scripts/generate-api.ts)
 * 出力先は OUT_DIR 環境変数で変更可 (既定 dist/api)
 */

import { mkdir, writeFile } from 'node:fs/promises'
import { join } from 'node:path'
import { fetchMultiModelForecast, fetchEnsembleForecast } from '../src/lib/open-meteo'
import { fetchAmedasStations, findNearestStation, fetchAmedasLatest } from '../src/lib/amedas'
import { computeConsensus, CONSENSUS_LABEL } from '../src/lib/consensus'
import { calculateHeadacheRisk } from '../src/lib/headache-model'
import { computeUmbrellaForecast } from '../src/lib/umbrella'
import type { AmedasObservation, HourlyPoint } from '../src/lib/types'
import { API_CITIES, type ApiCity } from './api-cities'

const OUT_DIR = process.env.OUT_DIR ?? join('dist', 'api')
const API_VERSION = 'v1'
const BASE_URL = 'https://moke-cloud.github.io/weather-tracker/api/v1'
const DOCS_URL = 'https://github.com/moke-cloud/weather-tracker/blob/main/API.md'
const ATTRIBUTION = [
  'Weather data by Open-Meteo.com (CC BY 4.0)',
  '観測データ: 気象庁 AMeDAS',
  'Generated by TenkiTracker (https://moke-cloud.github.io/weather-tracker/)',
]
/** 同時リクエスト数 (外部APIへの負荷配慮) */
const CONCURRENCY = 4
/** 公開APIに含める時間別予報の長さ */
const HOURLY_HORIZON_H = 48

interface Envelope<T> {
  success: boolean
  data: T | null
  error: string | null
  meta: {
    generatedAt: string
    version: string
    attribution: string[]
    [key: string]: unknown
  }
}

function envelope<T>(data: T, extraMeta: Record<string, unknown> = {}): Envelope<T> {
  return {
    success: true,
    data,
    error: null,
    meta: {
      generatedAt: new Date().toISOString(),
      version: API_VERSION,
      attribution: ATTRIBUTION,
      ...extraMeta,
    },
  }
}

/** 直近の実測 (取得失敗は null で続行) */
async function fetchObservation(city: ApiCity): Promise<AmedasObservation | null> {
  try {
    const stations = await fetchAmedasStations()
    const nearest = findNearestStation(stations, city.lat, city.lon)
    if (!nearest) return null
    return await fetchAmedasLatest(nearest.id)
  } catch {
    return null
  }
}

function compactHour(h: HourlyPoint) {
  const r = (v: number | null, digits = 1) =>
    v == null ? null : Math.round(v * 10 ** digits) / 10 ** digits
  return {
    time: h.time,
    temperature: r(h.temperature),
    apparentTemperature: r(h.apparentTemperature),
    weatherCode: h.weatherCode,
    pressureMsl: r(h.pressureMsl),
    precipitation: r(h.precipitation),
    precipitationProbability: r(h.precipitationProbability, 0),
    humidity: r(h.humidity, 0),
    windSpeed: r(h.windSpeed),
  }
}

interface CityResult {
  city: ApiCity
  payload: Record<string, unknown>
  summary: Record<string, unknown>
}

async function buildCity(city: ApiCity): Promise<CityResult> {
  const [forecast, ensemble, amedas] = await Promise.all([
    fetchMultiModelForecast(city.lat, city.lon),
    fetchEnsembleForecast(city.lat, city.lon),
    fetchObservation(city),
  ])

  const consensus = computeConsensus(forecast.models, amedas)
  if (!consensus) throw new Error(`${city.slug}: コンセンサス予報を生成できません`)

  const now = Date.now()
  const hourly = consensus.hourly.filter((h) => {
    const t = new Date(h.time).getTime()
    return t >= now - 3_600_000 && t <= now + HOURLY_HORIZON_H * 3_600_000
  })

  const risk = calculateHeadacheRisk(forecast.models, ensemble, { preferred: consensus })
  const umbrella = computeUmbrellaForecast(forecast.models, consensus, 48, now, ensemble)

  const current =
    hourly.find((h) => Math.abs(new Date(h.time).getTime() - now) <= 30 * 60_000) ??
    hourly[0] ?? null

  const payload = {
    location: {
      slug: city.slug,
      name: city.name,
      prefecture: city.pref,
      latitude: city.lat,
      longitude: city.lon,
    },
    current: current ? compactHour(current) : null,
    observation: amedas,
    hourly: hourly.map(compactHour),
    // past_days=3 を含む取得結果から当日以降のみ公開
    daily: forecast.daily.filter((d) => {
      const day = new Date(d.date)
      const today = new Date(now)
      today.setHours(0, 0, 0, 0)
      return day.getTime() >= today.getTime()
    }),
    headacheRisk: {
      score: risk.overallScore,
      level: risk.level,
      label: risk.label,
      summary: risk.summary,
      confidence: risk.confidence,
      factors: risk.factors.map((f) => ({
        id: f.id,
        name: f.name,
        score: f.score,
        weight: f.weight,
        description: f.description,
      })),
      hourly: risk.hourlyRisk,
    },
    umbrella: {
      summary: umbrella.summary,
      ranges: umbrella.ranges,
    },
    forecastSource: {
      blend: CONSENSUS_LABEL,
      models: ['JMA MSM', 'ECMWF IFS 0.25°', 'ICON', 'UKMO', 'GFS', 'GEM'],
      ensembles: ['ECMWF ENS (51)', 'NOAA GEFS (31)'],
      degraded: forecast.status !== 'ok',
    },
  }

  const summary = {
    slug: city.slug,
    name: city.name,
    prefecture: city.pref,
    url: `${BASE_URL}/cities/${city.slug}.json`,
    temperature: current ? compactHour(current).temperature : null,
    weatherCode: current?.weatherCode ?? null,
    headache: { score: risk.overallScore, level: risk.level, label: risk.label },
    umbrella: umbrella.ranges.length > 0 ? umbrella.summary : null,
  }

  return { city, payload, summary }
}

/** 並列数を制限しつつ全都市を処理 */
async function mapWithConcurrency<T, R>(
  items: T[],
  limit: number,
  fn: (item: T) => Promise<R>
): Promise<PromiseSettledResult<R>[]> {
  const results: PromiseSettledResult<R>[] = new Array(items.length)
  let index = 0

  async function worker() {
    while (index < items.length) {
      const i = index++
      try {
        results[i] = { status: 'fulfilled', value: await fn(items[i]) }
      } catch (reason) {
        results[i] = { status: 'rejected', reason }
      }
    }
  }

  await Promise.all(Array.from({ length: limit }, worker))
  return results
}

async function main() {
  const cityDir = join(OUT_DIR, API_VERSION, 'cities')
  await mkdir(cityDir, { recursive: true })

  console.log(`公開API生成開始: ${API_CITIES.length}都市 → ${OUT_DIR}/${API_VERSION}`)
  const results = await mapWithConcurrency(API_CITIES, CONCURRENCY, buildCity)

  const ok: CityResult[] = []
  const failed: string[] = []
  results.forEach((r, i) => {
    if (r.status === 'fulfilled') ok.push(r.value)
    else {
      failed.push(API_CITIES[i].slug)
      console.error(`  失敗: ${API_CITIES[i].slug}:`, r.reason)
    }
  })

  if (ok.length === 0) {
    throw new Error('全都市の生成に失敗しました。前回のデプロイ結果が維持されます。')
  }

  for (const { city, payload } of ok) {
    await writeFile(
      join(cityDir, `${city.slug}.json`),
      JSON.stringify(envelope(payload)),
      'utf8'
    )
  }

  await writeFile(
    join(OUT_DIR, API_VERSION, 'all.json'),
    JSON.stringify(
      envelope(
        ok.map((r) => r.summary),
        { total: ok.length, failedCities: failed }
      )
    ),
    'utf8'
  )

  const index = {
    name: 'TenkiTracker Public API',
    description:
      '47都道府県庁所在地の天気コンセンサス予報・頭痛リスク予測・傘予報。' +
      'キー不要・CORS対応。毎時更新 (GitHub Actions)。',
    docs: DOCS_URL,
    endpoints: {
      index: `${BASE_URL}/index.json`,
      allCities: `${BASE_URL}/all.json`,
      city: `${BASE_URL}/cities/{slug}.json`,
    },
    cities: API_CITIES.map((c) => ({
      slug: c.slug,
      name: c.name,
      prefecture: c.pref,
      url: `${BASE_URL}/cities/${c.slug}.json`,
    })),
  }
  await writeFile(
    join(OUT_DIR, API_VERSION, 'index.json'),
    JSON.stringify(envelope(index, { total: API_CITIES.length })),
    'utf8'
  )

  console.log(`生成完了: 成功 ${ok.length} / 失敗 ${failed.length}`)
  if (failed.length > 0) {
    console.log(`  失敗都市: ${failed.join(', ')}`)
  }
}

main().catch((err) => {
  console.error(err)
  process.exit(1)
})
